adjust tag logic

diff --git a/.github/workflows/tag-on-merge.yml b/.github/workflows/tag-on-merge.yml
--- a/.github/workflows/tag-on-merge.yml
+++ b/.github/workflows/tag-on-merge.yml
@@ -22,5 +22,10 @@ jobs:
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Run tag script
-        run: ./tag.sh
+      - name: Ensure version bump
+        run: |
+          ./tag.sh check_version $(find . -name "Version" -or -name "Versions") || (echo 'Version Bump Required' >> $FAIL_REASON;exit 1) && exit 0
+
+      - name: Tag this release
+        run: |
+          ./tag.sh $(find . -name "Version" -or -name "Versions" | cut -d/ -f2-) || (echo 'Failed to tag' >> $FAIL_REASON;exit 1) && exit 0
